version: '2'
services:
  webapp:
    build:
      context: .
      args:
        - FOLDER=$FOLDER
        - PASSWORD=$PASSWORD
    image: jupyterlab:0.1
    restart: always
    command: ["jupyter", "lab","--ip=0.0.0.0","--allow-root"]
    volumes:
      - ./$FOLDER:/$FOLDER
    ports:
      - 8888:8888
