version: '3'
services:
  webapp:
    build:
      context: .
      args:
        - FOLDER=$FOLDER
    image: jupyterlab:0.1
    restart: always
    volumes:
      - ./$FOLDER:/$FOLDER
    ports:
      - 8080:8888
